POST http://127.0.0.1:8000/api/races/1/comments/create/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMzA0NTI3LCJpYXQiOjE3MzIzMDA5MjcsImp0aSI6IjA1ZWU5MzUyNTIzNjRlMTQ5ZGIyMTY1MmE1YTAwZTA3IiwidXNlcl9pZCI6NX0.6OsCiDMwR5TbwYN-YpOq5kyhoVKeHz5U0wBDVqGRW_k
Content-Type: application/json

{
  "content": "Super"
}
