POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMTI3NjMwLCJpYXQiOjE3MzIxMjQwMzAsImp0aSI6IjlkZGE4NjRmZDE2MjQ4YmNiYjE1Y2M2ZDQxNDhhMGVmIiwidXNlcl9pZCI6Mn0.xS646sorkcI3Biz_Gr4ehrld1NZNpuDjyry0gLOsYps

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMjIxMDQzMCwiaWF0IjoxNzMyMTI0MDMwLCJqdGkiOiI2ZTJkODg5NzcxODk0MzA1ODBlZTEyYTJhMjdlOWI2YiIsInVzZXJfaWQiOjJ9.o9hzD3SaGrpHWD9RhmvN-r2yFcHL1jzwTpzYP1hO1J0"
}
