# Generated by Django 5.1.3 on 2024-11-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('constructor_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('previous_names', models.TextField(blank=True, null=True)),
                ('circuit_type', models.CharField(max_length=50)),
                ('place_name', models.CharField(max_length=100)),
                ('country_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
