# Generated by Django 5.1.3 on 2024-11-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0003_continent_alter_chassis_id_alter_circuit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha2_code', models.CharField(max_length=2)),
                ('alpha3_code', models.CharField(max_length=3)),
                ('demonym', models.CharField(max_length=100)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.continent')),
            ],
        ),
    ]
