# Generated by Django 5.1.3 on 2024-11-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0004_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constructor',
        ),
    ]
