# Generated by Django 5.1.3 on 2024-11-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0006_constructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chassis',
        ),
        migrations.DeleteModel(
            name='Circuit',
        ),
    ]
