# Generated by Django 5.1.3 on 2024-11-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0007_delete_chassis_delete_circuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chassis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.constructor')),
            ],
        ),
    ]
