# Generated by Django 5.1.3 on 2024-11-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0009_circuit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(max_length=10)),
                ('permanent_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('place_of_birth', models.CharField(max_length=100)),
                ('country_of_birth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_of_birth', to='WynikiF1.country')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nationality', to='WynikiF1.country')),
            ],
        ),
    ]
