# Generated by Django 5.1.3 on 2024-11-11 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0016_race_practicesession_pitstop_fastestlap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='name',
        ),
        migrations.CreateModel(
            name='SprintQualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('q1_time', models.CharField(blank=True, max_length=20, null=True)),
                ('q2_time', models.CharField(blank=True, max_length=20, null=True)),
                ('q3_time', models.CharField(blank=True, max_length=20, null=True)),
                ('gap', models.CharField(blank=True, max_length=20, null=True)),
                ('interval', models.CharField(blank=True, max_length=20, null=True)),
                ('laps', models.IntegerField()),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.driver')),
                ('engine_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.enginemanufacturer')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.race')),
                ('tyre_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.tyremanufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SprintRaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('time_penalty', models.CharField(blank=True, max_length=20, null=True)),
                ('gap', models.CharField(blank=True, max_length=20, null=True)),
                ('interval', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_retired', models.CharField(blank=True, max_length=200, null=True)),
                ('points', models.IntegerField()),
                ('grid_position', models.IntegerField()),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.driver')),
                ('engine_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.enginemanufacturer')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.race')),
                ('tyre_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.tyremanufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SprintStartingGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('grid_penalty', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.driver')),
                ('engine_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.enginemanufacturer')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.race')),
                ('tyre_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.tyremanufacturer')),
            ],
        ),
    ]
