# Generated by Django 5.1.3 on 2024-11-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0019_race_practicesession_pitstop_fastestlap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='status',
        ),
        migrations.AddField(
            model_name='raceresult',
            name='gap',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='grid_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='reason_retired',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='raceresult',
            name='time_penalty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
