# Generated by Django 5.1.3 on 2024-11-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0020_remove_raceresult_status_raceresult_gap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructorstanding',
            name='wins',
        ),
    ]
