# Generated by Django 5.1.3 on 2024-11-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0021_remove_constructorstanding_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverstanding',
            name='wins',
        ),
    ]
