# Generated by Django 5.1.3 on 2024-11-16 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0022_remove_driverstanding_wins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FastestLap',
        ),
    ]
