# Generated by Django 5.1.3 on 2024-11-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0024_fastestlap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fastestlap',
            name='position',
        ),
    ]
