# Generated by Django 5.1.3 on 2024-11-16 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0025_remove_fastestlap_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='grid_position',
        ),
    ]
