# Generated by Django 5.1.3 on 2024-11-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0027_alter_raceresult_laps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeSession',
        ),
    ]
