# Generated by Django 5.1.3 on 2024-11-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0028_delete_practicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField()),
                ('position', models.IntegerField()),
                ('laps', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=100)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.race')),
            ],
        ),
    ]
