# Generated by Django 5.1.3 on 2024-11-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0029_practicesession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicesession',
            name='status',
        ),
        migrations.AddField(
            model_name='practicesession',
            name='gap',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='practicesession',
            name='interval',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
