# Generated by Django 5.1.3 on 2024-11-16 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0030_remove_practicesession_status_practicesession_gap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintqualifyingresult',
            name='engine_manufacturer',
        ),
        migrations.RemoveField(
            model_name='sprintraceresult',
            name='engine_manufacturer',
        ),
        migrations.RemoveField(
            model_name='sprintstartinggrid',
            name='engine_manufacturer',
        ),
        migrations.CreateModel(
            name='QualifyingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('q1', models.CharField(blank=True, max_length=20, null=True)),
                ('q2', models.CharField(blank=True, max_length=20, null=True)),
                ('q3', models.CharField(blank=True, max_length=20, null=True)),
                ('laps', models.IntegerField(blank=True, null=True)),
                ('gap', models.CharField(blank=True, max_length=20, null=True)),
                ('interval', models.CharField(blank=True, max_length=20, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.constructor')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WynikiF1.race')),
            ],
        ),
    ]
