# Generated by Django 5.1.3 on 2024-11-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0031_remove_sprintqualifyingresult_engine_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualifyingresult',
            old_name='q1',
            new_name='q1_time',
        ),
        migrations.RenameField(
            model_name='qualifyingresult',
            old_name='q2',
            new_name='q2_time',
        ),
        migrations.RenameField(
            model_name='qualifyingresult',
            old_name='q3',
            new_name='q3_time',
        ),
    ]
