# Generated by Django 5.1.3 on 2024-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0034_remove_sprintraceresult_grid_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicesession',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintqualifyingresult',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sprintraceresult',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
