# Generated by Django 5.1.3 on 2024-11-16 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0035_alter_practicesession_laps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprintstartinggrid',
            name='constructor',
        ),
    ]
