# Generated by Django 5.1.3 on 2024-11-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0037_alter_practicesession_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='race',
            name='circuit_type',
        ),
    ]
