# Generated by Django 5.1.3 on 2024-12-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WynikiF1', '0040_remove_engine_manufacturer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PitStop',
        ),
    ]
